dark = {
    "theme_color": "#0069d9",
    "navbar": "navbar-dark",
    "bg": "bg-dark",
    "button": "btn-dark",
    "button_primary": "btn-primary",
    "button_outline_primary": "btn-outline-primary",
    "cross_back": "white",
    "background": "#343a40",
    "body_background": "#867f7f",
    "button_background": "#4a4a50",
    "dark_background": "#2a292e",
    "light_grey": "#434448",
    "hover_grey": "#434448",
    "theme_color": "#0069d9",
    "progress_theme": "#0069d9",
    "theme_color_light": "#0a59b3",
    "font": "#fff",
    "textbox_background": "#dbd6d6",
    "triangle_back": "#343a40",
    "triangle_hover": "#2a292e",
    "primary": "primary",
}
light = {
    "theme_color": "#3ea6cd",
    "navbar": "navbar-light",
    "bg": "bg-light",
    "button": "btn-info",
    "button_primary": "btn-info",
    "button_outline_primary": "btn-outline-info",
    "cross_back": "#121111",
    "background": "#c7c9ca",
    "body_background": "#e0dbdb",
    "button_background": "#4a4a50",
    "dark_background": "#c8c4d7",
    "light_grey": "#434448",
    "hover_grey": "#e0e2ea7a",
    "theme_color": "#3ea6cd",
    "progress_theme": "#2c91b7",
    "theme_color_light": "#3ea6cd",
    "font": "#383434",
    "textbox_background": "#dbd6d6",
    "triangle_back": "#17a2b8",
    "triangle_hover": "#138496",
    "primary": "info",
}
